version: '3.1'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on: [backend]
    ports:
      - "${VITE_DEV_SERVER_PORT}:8001"
    networks:
      - bj-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "${NODE_LOCAL_PORT}:3001"
    networks:
      - bj-network

networks:

  bj-network:
    driver: bridge
